# Build Stage
FROM node:18-alpine AS build

WORKDIR /app

COPY swiggyui/package*.json ./
RUN npm install

COPY swiggyui .
RUN npm run build


# Production Stage
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]